name: nightly
on:
  schedule:
    - cron: "0 6 * * *"
  # triggered manually
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build"
        type: string
        default: now
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
  build:
    needs: [checkout]
    uses: gardenlinux/gardenlinux/.github/workflows/build.yml@main
    with:
      version: ${{ inputs.version || 'now' }}
